steps:
- name: gcr.io/cloud-builders/curl
  entrypoint: bash
  args:
    - -c
    - |-
      echo "Original BRANCH_NAME: $BRANCH_NAME"
      echo "Manipulated BRANCH_NAME: $_BRANCH_NO_PREFIX"
      echo "Original BUILD_ID: $_BUILD_ID"
